---
# A simple playbook with Tendrl installation pre checks as listed in:
# https://tendrl.atlassian.net/browse/TEN-257

#
# Check hw requirements first, so far for *Tendrl Server* only.
#

- hosts: tendrl-server
  tasks:
    # Based on:
    #
    # > The Node hosting tendrl-api/central_store should have minimum 12
    # > GB of memory and 4 VCPUs (or equivalent)(due to alerts, logs
    # > being stored on this node)
    #
    # From https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.4.1-(install-doc)
    - assert:
        that:
          - ansible_memtotal_mb >= 12000
          - ansible_processor_vcpus >= 4

#
# General checks applicable to all machines.
#

- hosts: all
  user: root
  # become: yes
  tasks:

    - name: Check that we run on CentOS or Red Hat Enterprise Linux >= 7.3
      assert:
        that:
          - ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
          - ansible_distribution_major_version == '7'
          - ansible_distribution_version|regex_replace('7.3.*', '7.3') == '7.3'

    # Checking that NTP is configured. Based on RHEL 7 *System Administrators
    # Guide*.

    - name: Run timedatectl to see if NTP is enabled and synchronized
      command: timedatectl
      changed_when: False
      register: timedatectl_run

    - name: Check that NTP is enabled
      assert:
        that:
          - '"NTP enabled: yes" in timedatectl_run.stdout'

    - name: Check that NTP is synchronized
      assert:
        that:
          - '"NTP synchronized: yes" in timedatectl_run.stdout'

   # Check machine id.
   # TODO: Ok, there is a file in /etc/machine-id, but how to
   # check the uniqueness? actually, it's in ansible_machine_id

   # Check DNS setup.
   # check that ansible_fqdn translates to ip of default ansible interface?
