---
# A simple playbook with Tendrl installation pre checks as listed in:
# https://tendrl.atlassian.net/browse/TEN-257

#
# Check hw requirements first, so far for *Tendrl Server* only.
#

- hosts: tendrl-server
  tasks:
    # Based on:
    #
    # > The Node hosting tendrl-api/central_store should have minimum 12
    # > GB of memory and 4 VCPUs (or equivalent)(due to alerts, logs
    # > being stored on this node)
    #
    # From https://github.com/Tendrl/documentation/wiki/Tendrl-release-v1.4.1-(install-doc)
    - assert:
        that:
          - ansible_memtotal_mb >= 12000
          - ansible_processor_vcpus >= 4

#
# General checks applicable to all machines.
#

- hosts: all
  user: root
  # become: yes
  tasks:

    - name: Check that we run on CentOS or Red Hat Enterprise Linux >= 7.3
      assert:
        that:
          - ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
          - ansible_distribution_major_version == '7'
          - ansible_distribution_version|regex_replace('7.3.*', '7.3') == '7.3'

    # Checking that NTP is configured. Based on RHEL 7 *System Administrators
    # Guide* which states:
    #
    # > There is a choice between the daemons ntpd and chronyd, which are
    # > available from the repositories in the ntp and chrony packages
    # > respectively.
    #
    # It seems that for storage servers, ntpd makes more sense (referencing the
    # Admin guide again):
    #
    # > The NTP daemon (ntpd) should be considered for systems which are
    # > normally kept permanently on.
    #
    # But for POC virtual machines, there is nothing wrong with chrony I guess.
    #
    # Also note that we just check that the daemon is installed and running, in
    # a hope that it's already configured or that the defaults will work.
    # Ansible playbooks like this one can't possibly solve ntp configuration for
    # all possible enviroments.

    - name: Check if chrony is installed
      command: rpm -q chrony
      register: rpm_q_chrony
      changed_when: False
      failed_when: rpm_q_chrony.rc > 1

    - name: Check if ntp is installed
      command: rpm -q ntp
      register: rpm_q_ntp
      changed_when: False
      failed_when: rpm_q_ntp.rc > 1

    - name: Check that either chrony or ntp is installed
      assert:
        that:
          - rpm_q_chrony.rc == 0 or rpm_q_ntp.rc == 0

    - name: Try to start chronyd service, if only chrony is installed
      service: name=chronyd state=started
      when: rpm_q_chrony.rc == 0 and rpm_q_ntp.rc != 0
      register: chronyd_service

    - name: Try to start ntpd service, if it makes sense
      service: name=ntpd state=started
      # TODO: we don't want to start ntpd if chronyd is running
      when: rpm_q_ntp.rc == 0 and (rpm_q_chrony.rc != 0 or chronyd_service.state != "started")
      register: ntpd_service

    - name: Check that either chronyd or ntpd service is running
      assert:
        that:
          - chronyd_service is defined or ntpd_service is defined
          # - chronyd_service is defined and chronyd_service.state == "started"
          # - ntpd_service is defined and ntpd_service.state == "started"

   # Check machine id.
   # TODO: Ok, there is a file in /etc/machine-id, but how to
   # check the uniqueness? actually, it's in ansible_machine_id

   # Check DNS setup.
   # check that ansible_fqdn translates to ip of default ansible interface?
