---

- name: Install firewalld
  yum:
    name=firewalld
    state=present

- name: Ensure that firewalld is started and enable at boot
  service:
    name=firewalld
    enabled=yes
    state=started

- name: Gluster native events webhook
  firewalld:
    port=8697/tcp
    permanent=yes
    state=enabled
  notify:
    - restart firewalld
