---

- name: Install tendrl-node-agent
  yum:
    name=tendrl-node-agent
    state=latest

- name: Configure etcd and graphite ip addr in node-agent.conf.yaml
  lineinfile:
    dest: /etc/tendrl/node-agent/node-agent.conf.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^etcd_connection:.*'
      line: "etcd_connection: {{ etcd_ip_address }}"
    - regexp: '^graphite_host:.*'
      line: "graphite_host: {{ graphite_ip_address }}"
  notify:
    - restart tendrl-node-agent

- name: Add provisioner/gluster tag into node-agent.conf.yaml
  lineinfile:
    dest: /etc/tendrl/node-agent/node-agent.conf.yaml
    insertafter: '^tags:$'
    line: "  - provisioner/gluster"
  notify:
    - restart tendrl-node-agent
  when: tendrl_gluster_provisioning_support == True
  run_once: true

- name: Enable tendrl-node-agent service
  service:
    name=tendrl-node-agent
    enabled=yes

- name: Start tendrl-node-agent service
  service:
    name=tendrl-node-agent
    state=started
