---
# handlers file for tendrl-server

- name: restart etcd
  service:
    name=etcd
    state=restarted

- name: restart tendrl-api
  service:
    name=tendrl-api
    state=restarted

- name: restart httpd
  service:
    name=httpd
    state=restarted

- name: restart tendrl-node-agent
  service:
    name=tendrl-node-agent
    state=restarted

- name: restart tendrl-alerting
  service:
    name=tendrl-alerting
    state=restarted

- name: restart tendrl-node-monitoring
  service:
    name=tendrl-node-monitoring
    state=restarted
