---

- name: Collect etcd server address
  set_fact:
    etcd_server_address: "{{ hostvars[groups['tendrl-servers'][0]]['ansible_default_ipv4']['address'] }}"

- name: DEBUG!
  debug:
    msg: "Using {{ etcd_server_address }} to connect to server"

- name: Install tendrl repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/repo/epel-7/tendrl-tendrl-epel-7.repo
    dest: /etc/yum.repos.d/tendrl-tendrl-epel-7.repo

- name: Disable SELinux
  selinux:
    state: disabled

- name: Activate EPEL
  package:
    name: http://mirror.netcologne.de/fedora-epel/epel-release-latest-7.noarch.rpm

# This needs the RHEL extra repo
- name: Ensure tendrl-node-agent is installed
  package:
    name: tendrl-node-agent
    state: latest

- name: Configure etcd connection for tendrl-node-agent
  lineinfile:
    dest: /etc/tendrl/node-agent/node-agent.conf.yaml
    line: "etcd_connection = '{{ etcd_server_address }}'"
    regexp: '^etcd_connection'

- name: Start tendrl-node-agent and enable it on boot
  service:
    name: tendrl-node-agent
    enabled: yes
    state: restarted

# This needs the RHEL extra repo
- name: Ensure tendrl-gluster-integration is installed
  package:
    name: tendrl-gluster-integration
    state: latest

- name: Start tendrl-gluster-integration and enable it on boot
  service:
    name: tendrl-glusterd
    enabled: yes
    state: restarted

# http://IP:2379/v2/keys/nodes should list all nodes
