---
# tasks file for tendrl-performance-monitoring

- name: Install tendrl-performance-monitoring
  package:
    name=tendrl-performance-monitoring
    state=latest
  notify:
    - restart httpd

- name: Initialize graphite-db
  command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput
  args:
    creates: /var/lib/graphite-web/graphite.db
  register: graphite_syncdb

- debug: msg={{ graphite_syncdb.stdout }}

- name: Allow apache to access graphite.db file
  file:
    path: /var/lib/graphite-web/graphite.db
    owner: apache
    group: apache

- name: Start carbon-cache service
  service:
    name=carbon-cache
    state=started

- name: Enable carbon-cache service
  service:
    name=carbon-cache
    enabled=yes

- name: Configure tendrl-performance monitoring
  lineinfile:
    dest=/etc/tendrl/performance-monitoring/performance-monitoring.conf.yaml
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: '^etcd_connection:.*'
      line: "etcd_connection: {{ etcd_ip_address }}"
    - regexp: '^time_series_db_server:.*'
      line: "time_series_db_server: {{ ansible_default_ipv4['address'] }}"
    - regexp: '^api_server_addr:.*'
      line: "api_server_addr: {{ tendrl_api_ip_address }}"
  notify:
    - restart tendrl-performance-monitoring

- name: Start tendrl-performance-monitoring service
  service:
    name=tendrl-performance-monitoring
    state=started

- name: Enable tendrl-performance-monitoring service
  service:
    name=tendrl-performance-monitoring
    enabled=yes
