---
# tasks file for installation and setup of etcd for the purposes of Tendrl

- name: Install etcd
  yum:
    name=etcd
    state=present

- name: Configure etcd.conf ETCD_LISTEN_CLIENT_URLS
  lineinfile:
    dest=/etc/etcd/etcd.conf
    regexp="^(\#*)ETCD_LISTEN_CLIENT_URLS(.*)"
    line="ETCD_LISTEN_CLIENT_URLS=\"http://{{ etcd_ip_address }}:2379\""
  notify:
    - restart etcd

- name: Configure etcd.conf ETCD_ADVERTISE_CLIENT_URLS
  lineinfile:
    dest=/etc/etcd/etcd.conf
    regexp="^(\#*)ETCD_ADVERTISE_CLIENT_URLS(.*)"
    line="ETCD_ADVERTISE_CLIENT_URLS=\"http://{{ etcd_ip_address }}:2379\""
  notify:
    - restart etcd

- name: Enable etcd service
  service:
    name=etcd
    enabled=yes

- name: Start etcd service
  service:
    name=etcd
    state=started

- meta: flush_handlers
