---

- name: Collect etcd server address
  set_fact:
    etcd_server_address: "{{ hostvars[groups['tendrl-servers'][0]]['ansible_default_ipv4']['address'] }}"

- name: DEBUG!
  debug:
    msg: "Using {{ etcd_server_address }} to connect to etcd server"

- name: Install tendrl repo
  get_url:
    url: https://copr.fedorainfracloud.org/coprs/tendrl/tendrl/repo/epel-7/tendrl-tendrl-epel-7.repo
    dest: /etc/yum.repos.d/tendrl-tendrl-epel-7.repo

- name: Disable SELinux
  selinux:
    state: disabled

- name: Activate EPEL
  package:
    name: http://mirror.netcologne.de/fedora-epel/epel-release-latest-7.noarch.rpm

# This needs the RHEL extras repo!
# TODO: do a version compare instead of hard code etcd version
- name: Ensure etcd is installed
  package:
    name: etcd-2.3.7-4.el7
    state: present

- name: Configure etcd
  replace:
    dest: /etc/etcd/etcd.conf
    regexp: 'localhost'
    replace: '{{ etcd_server_address }}'

- name: Start etcd and enable it on boot
  service:
    name: etcd
    enabled: yes
    state: restarted

- name: Check if etcd is OK
  uri:
    url: 'http://{{ etcd_server_address }}:2379/v2/keys'

- name: Install tendrl-apid
  package:
    name: tendrl-api
    state: latest

- name: Configure tendrl-apid connection to etcd - hostname
  lineinfile:
    dest: /etc/tendrl/etcd.yml
    line: "  :host: '{{ etcd_server_address }}'"
    regexp: ':host:'

- name: Configure tendrl-apid connection to etcd - username
  lineinfile:
    dest: /etc/tendrl/etcd.yml
    line: "  :user_name: ''"
    regexp: ':user_name:'

- name: Configure tendrl-apid connection to etcd - password
  lineinfile:
    dest: /etc/tendrl/etcd.yml
    line: "  :password: ''"
    regexp: ':password:'

- name: Start tendrl-apid and enable it on boot
  service:
    name: tendrl-apid
    enabled: yes
    state: restarted

- name: Check if tendrl-apid is OK
  uri:
    url: 'http://{{ etcd_server_address }}:9292/1.0/ping'
  ignore_errors: yes

- name: Install tendrl-dashboard
  package:
    name: tendrl-dashboard
    state: latest

# curl -XGET http://IP:9292/1.0/ping <--  Check if API server is running
# curl -XGET http://IP:9292/1.0/GetNodeList <-- Return List of nodes running tendrl-noded
# curl -XPOST -d '{"Node[]": ["node_id1","node_id2","node_id3"], "Tendrl_context.sds_name":"gluster", Tendrl_context.sds_version:"gluster-version"}' http://IP:9292/1.0/GlusterImportCluster <-- Import existing Gluster Storage Pool
