---

- name: Collect etcd server address
  set_fact:
    etcd_server_address: '{{ ansible_default_ipv4.address }}'

- name: Disable SELinux
  selinux:
    state: disabled

- name: Ensure etcd is installed
  apt:
    name: etcd
    state: latest

- name: Configure etcd
  replace:
    dest: /etc/etcd/etcd.conf
    regexp: 'localhost'
    replace: '{{ etcd_server_address }}'

- service:
    name: etcd
    enabled: yes
    state: started

- name: Check if etcd is OK
  uri:
    url: 'http://{{ etcd_server_address }}:2379/v2/keys'

- name: Install tendlr-api
  apt:
    name: tendrl-api
    state: latest

- name: Configure tendrl-api connection to etcd - hostname
  lineinfile:
    dest: /etc/tendrl/etcd.yml
    line: ":host: '{{ etcd_server_address }}'"
    regexp: ':host:'

- name: Configure tendrl-api connection to etcd - username
  lineinfile:
    dest: /etc/tendrl/etcd.yml
    line: ":user_name: ''"
    regexp: ':user_name:'

- name: Configure tendrl-api connection to etcd - password
  lineinfile:
    dest: /etc/tendrl/etcd.yml
    line: ":password: ''"
    regexp: ':password:'

- service:
    name: tendrl-apid
    enabled: yes
    state: started

- name: Check if tendrl-api is OK
  uri:
    url: 'http://{{ etcd_server_address }}:9292/1.0/ping'

# curl -XGET http://IP:9292/1.0/ping <--  Check if API server is running
# curl -XGET http://IP:9292/1.0/GetNodeList <-- Return List of nodes running tendlr-noded
# curl -XPOST -d '{"Node[]": ["node_id1","node_id2","node_id3"], "Tendrl_context.sds_name":"gluster", Tendrl_context.sds_version:"gluster-version"}' http://IP:9292/1.0/GlusterImportCluster <-- Import existing Gluster Storage Pool
