---
# tasks file for tendrl-server

- name: Use ip address of default ipv4 network interface for graphite
  set_fact:
    graphite_ip_address: '{{ ansible_default_ipv4.address }}'
  when: graphite_ip_address is undefined

- debug:
    msg:
      - "Using {{ etcd_fqdn }} as etcd fqdn in tendrl config files."
      - "Using {{ etcd_ip_address }} as etcd ip address in etcd config file."
      - "Using {{ graphite_ip_address }} as graphite ip address."

- include: etcd.yml
- include: tendrl-node-agent.yml
- include: tendrl-api.yml
- include: tendrl-ui.yml
- include: tendrl-monitoring-integration.yml
- include: tendrl-notifier.yml

- name: Enable httpd service
  service:
    name=httpd
    enabled=yes

- name: Start httpd service
  service:
    name=httpd
    state=started
