---
# tasks file for tendrl-server

- name: Use ip address of default ipv4 network interface for etcd
  set_fact:
    etcd_ip_address: '{{ ansible_default_ipv4.address }}'
  when: etcd_ip_address is undefined

- debug:
    msg: "Using {{ etcd_ip_address }} as etcd ip address."

- include: etcd.yml
- include: tendrl-api.yml
- include: tendrl-node-agent.yml
- include: tendrl-alerting.yml

- name: Install tendrl-dashboard
  yum:
    name=tendrl-dashboard
    state=latest
  notify:
    - restart httpd
