---

- name: Install tendrl-node-agent
  yum:
    name=tendrl-node-agent
    state=latest

- name: Configure etcd_connection in node-agent.conf.yaml
  lineinfile:
    dest: /etc/tendrl/node-agent/node-agent.conf.yaml
    regexp: '^etcd_connection:.*'
    line: "etcd_connection: {{ etcd_ip_address }}"
  notify:
    - restart tendrl-node-agent

- name: Enable tendrl-node-agent service
  service:
    name=tendrl-node-agent
    enabled=yes

- name: Start tendrl-node-agent service
  service:
    name=tendrl-node-agent
    state=started
