---

- name: Install tendrl-alerting
  yum:
    name=tendrl-alerting
    state=latest

- name: Configure etcd_connection in alerting.conf.yaml
  lineinfile:
    dest: /etc/tendrl/alerting/alerting.conf.yaml
    regexp: '^etcd_connection:.*'
    line: "etcd_connection: {{ etcd_ip_address }}"
  notify:
    - restart tendrl-alerting

# TODO: add full tweakability (and edit port, auth and password as well)
- name: Configure email source in email.conf.yaml
  lineinfile:
    dest: /etc/tendrl/alerting/email.conf.yaml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^email_id.*'
      line: "email_id: {{ tendrl_alerting_email_id }}"
    - regexp: '^email_smtp_server.*'
      line: "email_smtp_server: {{ tendrl_alerting_email_smtp_server }}"
  when: tendrl_alerting_email_id is defined and tendrl_alerting_email_smtp_server is defined
  notify:
    - restart tendrl-alerting

- name: Enable tendrl-alerting service
  service:
    name=tendrl-alerting
    enabled=yes

- name: Start tendrl-alerting service
  service:
    name=tendrl-alerting
    state=started
