---

- name: Install tendrl-monitoring-integration
  yum:
    name=tendrl-monitoring-integration
    state=latest

- name: Initialize graphite-db
  command: /usr/lib/python2.7/site-packages/graphite/manage.py syncdb --noinput
  args:
    creates: /var/lib/graphite-web/graphite.db
  register: graphite_syncdb

- debug: msg={{ graphite_syncdb.stdout }}

- name: Allow apache to access graphite.db file
  file:
    path: /var/lib/graphite-web/graphite.db
    owner: apache
    group: apache

- name: Start carbon-cache service
  service:
    name=carbon-cache
    state=started

- name: Enable carbon-cache service
  service:
    name=carbon-cache
    enabled=yes

- name: Enable grafana-server service
  service:
    name=grafana-server
    enabled=yes
    daemon_reload=yes

- name: Start grafana-server service
  service:
    name=grafana-server
    state=started

- name: Configure tendrl-monitoring-integration
  lineinfile:
    dest=/etc/tendrl/monitoring-integration/monitoring-integration.conf.yaml
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - regexp: '^datasource_host:.*'
      line: "datasource_host: {{ graphite_ip_address }}"

# Script tendrl-monitoring-integration requires grafana to be up and running,
# but sometimes grafana is not able to respong to queries at this point and
# so the tendrl-monitoring-integration script fails. For this reason, when the
# script fails, we try to rerun after waiting for 5s again (and try this for
# another 4 times before giving up and reporting an error).
#
# Script tendrl-monitoring-integration uploads dashboard definitions into
# grafana and without this step, you would not see any dashboards there.

- name: Run tendrl-monitoring-integration
  command: /usr/bin/tendrl-monitoring-integration
  register: tmi_result
  changed_when:
    - "'Datasource  uploaded successfully' in tmi_result.stdout"
  failed_when:
    - "('upload failed' in tmi_result.stdout and not 'Data source with same name already exists' in tmi_result.stdout) or tmi_result.stderr != ''"
  until: tmi_result|success
  retries: 5
  delay: 5

- debug:
    msg:
      - "tendrl-monitoring-integration stdout: {{ tmi_result.stdout }}"
      - "tendrl-monitoring-integration stderr: {{ tmi_result.stderr }}"
