---
# handlers file for tendrl-node

- name: restart tendrl-node-agent
  service:
    name=tendrl-node-agent
    state=restarted

- name: restart rsyslog
  service:
    name=rsyslog
    state=restarted

- name: restart firewalld
  service:
    name=firewalld
    state=restarted
